In [15]:
from sklearn.cluster import DBSCAN
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
import csv
import numpy as np
import pandas as pd



1.2

In [2]:
df = pd.read_excel('C:/Users/Hussein/Documents/cheating.xls')

"""
X = np.array([ 
            [1,2,3,4,0,123311244126673224],
            [1,2,3,4,0,599283748348574587],
            [1,2,1,2,0,598298745987234987],
            [1,2,4,3,1,945689734598745689],
            [3,2,4,1,1,232498745987345987],
            [3,2,4,1,1,123983459839843589],
            [1,2,3,4,0,121398734897584875]
            ])
 
"""
training_data = pd.read_excel("C:/Users/Hussein/Documents/cheating.xls")
 
X  = training_data.as_matrix()
X

c:\users\hussein\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:19: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


array([[ 1,  5,  9, 13],
       [ 2,  6,  9, 14],
       [ 3,  7, 10, 15],
       [ 4,  8, 11, 16],
       [ 4,  6, 12, 16],
       [ 2,  6, 12, 16],
       [ 4,  7, 12, 14],
       [ 2,  7, 11, 14],
       [ 4,  8, 10, 15],
       [ 3,  5, 10, 15],
       [ 3,  5, 10, 14],
       [ 1,  6, 11, 13],
       [ 2,  7, 12, 13],
       [ 2,  8, 10, 13],
       [ 4,  6, 12, 15],
       [ 4,  6,  9, 16],
       [ 3,  7,  9, 13],
       [ 2,  8, 11, 13],
       [ 1,  8, 11, 16],
       [ 2,  6, 12, 14],
       [ 3,  5,  9, 15],
       [ 4,  5,  9, 15],
       [ 4,  7, 12, 15],
       [ 2,  8, 11, 16],
       [ 2,  5, 11, 13],
       [ 3,  8, 12, 13],
       [ 3,  8,  9, 15],
       [ 1,  6, 10, 15],
       [ 1,  6, 10, 16],
       [ 1,  4, 11, 16],
       [ 2,  7, 12, 13],
       [ 2,  8,  9, 13],
       [ 3,  5, 10, 13],
       [ 1,  6, 11, 14],
       [ 4,  8, 10, 15],
       [ 4,  5, 10, 16],
       [50, 20, 30, 40],
       [50, 20, 30, 40]], dtype=int64)

In [14]:
#dbscan = DBSCAN(eps =   3, min_samples = 5)
#kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
bandwidth = np.array([1.0, 1.2, 1.3, 1.5, 1.7, 1.8, 2.0], dtype=float)

clustering = []

j = 0
for i in bandwidth:
    
    clustering[j] = MeanShift(bandwidth = bandwidth[i]).fit(X)
    j = j + 1

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [55]:
#model = dbscan.fit(X)
#kmeans.labels_
clustering.labels_

array([0, 0, 1, 1, 2, 2, 2, 0, 1, 0, 0, 0, 3, 3, 2, 1, 3, 3, 5, 0, 0, 0,
       2, 5, 0, 3, 1, 0, 6, 6, 3, 3, 0, 0, 1, 2, 4, 4], dtype=int64)

In [150]:
#print(model.labels_)
clustering.predict([[50, 20, 30, 40]])

array([4], dtype=int64)